### ISSUE TITLE
PCB Schematic and Gerber Design files for reference

### ISSUE THREAD

**Issue by AshishESP** [RomanAlexandroff/IoT-Name-Badge-ESP32#2]
Hi @RomanAlexandroff , I need to make my own board based on this. can you please help yo share all PCB design files of this board please?

**Comment by RomanAlexandroff** [comment]
Hi, @AshishESP! Thank you for your interest in the project!
At this moment I do not intend to make it a single board device, so I have never created a PCB schematic for it.

Perhaps, it would be useful for you to know that the project is targeted for the following hardware:

Display:
WeAct 2.9" 296x128 Black-and-White SPI E-paper Module
https://www.aliexpress.com/item/1005004644515880.html?gps-id=pcStoreLeaderboard&scm=1007.22922.271278.0&scm_id=1007.22922.271278.0&scm-url=1007.22922.271278.0&pvid=62078f9e-1dd6-4865-bc8b-55a5b6728024&_t=gps-id:pcStoreLeaderboard,scm-url:1007.22922.271278.0,pvid:62078f9e-1dd6-4865-bc8b-55a5b6728024,tpp_buckets:668%232846%238109%231935&pdp_npi=4%40dis%21CZK%21175.91%2141.86%21%21%2154.33%21%21%402101e9a216958346659896012e95a6%2112000031468032209%21rec%21CZ%21%21AB&spm=a2g0o.store_pc_home.smartLeaderboard_2004270797047.1005004644515880

Microcontroller:
ESP-C3-01M (ESP32) module
https://www.aliexpress.com/item/1005002885898138.html?spm=a2g0n.order_detail.order_detail_item.3.677af19cEeEALH
